# Generated by Django 3.0.3 on 2020-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='post/<django.db.models.fields.CharField>/img/')),
            ],
        ),
    ]
