# Generated by Django 3.0.3 on 2020-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20200217_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
