# Generated by Django 3.0.3 on 2020-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=256),
        ),
    ]
