# Generated by Django 3.0.3 on 2020-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20200217_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
