# Generated by Django 3.0.3 on 2020-03-01 11:57

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_auto_20200301_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no-img.png', upload_to=blog.utils.file_path_gen),
        ),
    ]
