# Generated by Django 3.0.3 on 2020-03-01 12:02

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20200301_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to=blog.utils.file_path_gen),
        ),
    ]
