# Generated by Django 3.0.3 on 2020-03-02 21:54

import blog.utils
from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_auto_20200301_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(default='no-img.png', upload_to=blog.utils.file_path_gen),
        ),
    ]
