# Generated by Django 3.0.3 on 2020-03-03 09:36

import blog.utils
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0013_auto_20200302_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no-img.png', upload_to=blog.utils.file_path_gen),
        ),
    ]
