# Generated by Django 3.0.4 on 2020-03-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0014_auto_20200303_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
