# Generated by Django 3.0.4 on 2020-03-18 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0016_auto_20200317_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
