# Generated by Django 3.0.4 on 2020-03-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0017_auto_20200318_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubcription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
