# Generated by Django 3.0.4 on 2020-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0019_auto_20200319_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
